# Generated by Django 5.2.7 on 2025-10-07 13:02

import django.db.models.deletion
import utils.image_tools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField(verbose_name='Quantidade de carros')),
                ('cars_value', models.FloatField(verbose_name='Valor total dos carros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da contagem')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Opcional')),
            ],
            options={
                'verbose_name': 'Opcional',
                'verbose_name_plural': 'Opcionais',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('version', models.CharField(max_length=64, verbose_name='Versão')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('ai_description', models.BooleanField(default=False, verbose_name='Descrição Automática')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('mileage', models.IntegerField(verbose_name='Quilometragem')),
                ('transmission', models.CharField(choices=[('AT', 'Automática'), ('MT', 'Manual'), ('CVT', 'CVT')], max_length=16, verbose_name='Transmissão')),
                ('color', models.CharField(verbose_name='Cor')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.cover_upload_path, verbose_name='Capa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('status', models.CharField(choices=[('SOLD', 'Vendido'), ('AVAILABLE', 'Disponível'), ('OLD_STOCK', 'Estoque Antigo')], default='AVAILABLE', max_length=16, verbose_name='Status')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Vendido em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_brand', to='cars.brand', verbose_name='Marca')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('optionals', models.ManyToManyField(blank=True, related_name='car_optional', to='cars.optional', verbose_name='Opcionais')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_view', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.photo_upload_path, verbose_name='Visão frontal')),
                ('side_view', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.photo_upload_path, verbose_name='Visão lateral')),
                ('back_view', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.photo_upload_path, verbose_name='Visão traseira')),
                ('interior_view', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.photo_upload_path, verbose_name='Visão interior')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cars.car')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
    ]
