# Generated by Django 5.2.7 on 2025-10-07 13:02

import utils.image_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição curta do site para SEO', verbose_name='Descrição do Site')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.favicon_upload_path, verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.logo_upload_path, verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.banner_upload_path, verbose_name='Banner')),
                ('unknown_car', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.unknown_car_upload_path, verbose_name='Carro Desconhecido')),
                ('header_title', models.CharField(blank=True, help_text='O título principal exibido na página inicial.', max_length=128, verbose_name='Título do header princial')),
                ('header_subtitle', models.TextField(blank=True, help_text='O texto de apoio exibido abaixo do título principal.', verbose_name='Subtítulo do Header')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Endereço')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato')),
                ('phone_number', models.CharField(blank=True, help_text='Ex: 5562912345678 (Código do País + Código de Área + Número)', max_length=13, verbose_name='Número de Telefone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Ex: 5562912345678 (Código do País + Código de Área + Número)', max_length=13, verbose_name='Número do Whatsapp')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Link do Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Link do X/Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Link do Instagram')),
                ('about', models.TextField(blank=True, help_text='Texto a ser exibido no footer.', verbose_name='Sobre')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
